// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Department is the predicate function for department builders.
type Department func(*sql.Selector)

// Project is the predicate function for project builders.
type Project func(*sql.Selector)

// ProjectAssignment is the predicate function for projectassignment builders.
type ProjectAssignment func(*sql.Selector)

// Role is the predicate function for role builders.
type Role func(*sql.Selector)

// Timesheet is the predicate function for timesheet builders.
type Timesheet func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
