// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package tools

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type AssignUserInput struct {
	UserID         string      `json:"userId"`
	ProjectID      string      `json:"projectId"`
	ProjectRole    ProjectRole `json:"projectRole"`
	AllocatedHours float64     `json:"allocatedHours"`
}

type AuthPayload struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type CreateDepartmentInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
}

type CreateProjectInput struct {
	Name         string     `json:"name"`
	Description  *string    `json:"description,omitempty"`
	DepartmentID string     `json:"departmentId"`
	StartDate    *time.Time `json:"startDate,omitempty"`
	EndDate      *time.Time `json:"endDate,omitempty"`
}

type DashboardStats struct {
	TotalUsers       int     `json:"totalUsers"`
	TotalProjects    int     `json:"totalProjects"`
	ActiveProjects   int     `json:"activeProjects"`
	TotalHoursLogged float64 `json:"totalHoursLogged"`
}

type Department struct {
	ID          string     `json:"id"`
	Name        string     `json:"name"`
	Description *string    `json:"description,omitempty"`
	CreatedAt   time.Time  `json:"createdAt"`
	Users       []*User    `json:"users,omitempty"`
	Projects    []*Project `json:"projects,omitempty"`
}

type LogTimesheetInput struct {
	UserID      string    `json:"userId"`
	ProjectID   string    `json:"projectId"`
	Date        time.Time `json:"date"`
	HoursWorked float64   `json:"hoursWorked"`
	Description *string   `json:"description,omitempty"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Project struct {
	ID          string               `json:"id"`
	Name        string               `json:"name"`
	Description *string              `json:"description,omitempty"`
	Status      ProjectStatus        `json:"status"`
	StartDate   *time.Time           `json:"startDate,omitempty"`
	EndDate     *time.Time           `json:"endDate,omitempty"`
	CreatedAt   time.Time            `json:"createdAt"`
	UpdatedAt   time.Time            `json:"updatedAt"`
	Department  *Department          `json:"department,omitempty"`
	Assignments []*ProjectAssignment `json:"assignments,omitempty"`
	Timesheets  []*Timesheet         `json:"timesheets,omitempty"`
}

type ProjectAssignment struct {
	ID             string      `json:"id"`
	ProjectRole    ProjectRole `json:"projectRole"`
	AllocatedHours float64     `json:"allocatedHours"`
	AssignedAt     time.Time   `json:"assignedAt"`
	User           *User       `json:"user"`
	Project        *Project    `json:"project"`
}

type Query struct {
}

type RegisterInput struct {
	FirstName    string `json:"firstName"`
	LastName     string `json:"lastName"`
	Email        string `json:"email"`
	Password     string `json:"password"`
	RoleID       string `json:"roleId"`
	DepartmentID string `json:"departmentId"`
}

type Role struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description,omitempty"`
	CreatedAt   time.Time `json:"createdAt"`
	Users       []*User   `json:"users,omitempty"`
}

type Timesheet struct {
	ID          string          `json:"id"`
	Date        time.Time       `json:"date"`
	HoursWorked float64         `json:"hoursWorked"`
	Description *string         `json:"description,omitempty"`
	Status      TimesheetStatus `json:"status"`
	CreatedAt   time.Time       `json:"createdAt"`
	UpdatedAt   time.Time       `json:"updatedAt"`
	User        *User           `json:"user"`
	Project     *Project        `json:"project"`
}

type UpdateProjectInput struct {
	Name        *string        `json:"name,omitempty"`
	Description *string        `json:"description,omitempty"`
	Status      *ProjectStatus `json:"status,omitempty"`
	StartDate   *time.Time     `json:"startDate,omitempty"`
	EndDate     *time.Time     `json:"endDate,omitempty"`
}

type UpdateTimesheetStatusInput struct {
	TimesheetID string          `json:"timesheetId"`
	Status      TimesheetStatus `json:"status"`
}

type User struct {
	ID          string               `json:"id"`
	FirstName   string               `json:"firstName"`
	LastName    string               `json:"lastName"`
	Email       string               `json:"email"`
	Status      UserStatus           `json:"status"`
	CreatedAt   time.Time            `json:"createdAt"`
	UpdatedAt   time.Time            `json:"updatedAt"`
	Role        *Role                `json:"role,omitempty"`
	Department  *Department          `json:"department,omitempty"`
	Assignments []*ProjectAssignment `json:"assignments,omitempty"`
	Timesheets  []*Timesheet         `json:"timesheets,omitempty"`
}

type ProjectRole string

const (
	ProjectRoleLead      ProjectRole = "lead"
	ProjectRoleDeveloper ProjectRole = "developer"
	ProjectRoleDesigner  ProjectRole = "designer"
	ProjectRoleTester    ProjectRole = "tester"
	ProjectRoleAnalyst   ProjectRole = "analyst"
)

var AllProjectRole = []ProjectRole{
	ProjectRoleLead,
	ProjectRoleDeveloper,
	ProjectRoleDesigner,
	ProjectRoleTester,
	ProjectRoleAnalyst,
}

func (e ProjectRole) IsValid() bool {
	switch e {
	case ProjectRoleLead, ProjectRoleDeveloper, ProjectRoleDesigner, ProjectRoleTester, ProjectRoleAnalyst:
		return true
	}
	return false
}

func (e ProjectRole) String() string {
	return string(e)
}

func (e *ProjectRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ProjectRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ProjectRole", str)
	}
	return nil
}

func (e ProjectRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ProjectRole) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ProjectRole) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ProjectStatus string

const (
	ProjectStatusPlanning  ProjectStatus = "planning"
	ProjectStatusActive    ProjectStatus = "active"
	ProjectStatusOnHold    ProjectStatus = "on_hold"
	ProjectStatusCompleted ProjectStatus = "completed"
	ProjectStatusCancelled ProjectStatus = "cancelled"
)

var AllProjectStatus = []ProjectStatus{
	ProjectStatusPlanning,
	ProjectStatusActive,
	ProjectStatusOnHold,
	ProjectStatusCompleted,
	ProjectStatusCancelled,
}

func (e ProjectStatus) IsValid() bool {
	switch e {
	case ProjectStatusPlanning, ProjectStatusActive, ProjectStatusOnHold, ProjectStatusCompleted, ProjectStatusCancelled:
		return true
	}
	return false
}

func (e ProjectStatus) String() string {
	return string(e)
}

func (e *ProjectStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ProjectStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ProjectStatus", str)
	}
	return nil
}

func (e ProjectStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ProjectStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ProjectStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TimesheetStatus string

const (
	TimesheetStatusDraft     TimesheetStatus = "draft"
	TimesheetStatusSubmitted TimesheetStatus = "submitted"
	TimesheetStatusApproved  TimesheetStatus = "approved"
	TimesheetStatusRejected  TimesheetStatus = "rejected"
)

var AllTimesheetStatus = []TimesheetStatus{
	TimesheetStatusDraft,
	TimesheetStatusSubmitted,
	TimesheetStatusApproved,
	TimesheetStatusRejected,
}

func (e TimesheetStatus) IsValid() bool {
	switch e {
	case TimesheetStatusDraft, TimesheetStatusSubmitted, TimesheetStatusApproved, TimesheetStatusRejected:
		return true
	}
	return false
}

func (e TimesheetStatus) String() string {
	return string(e)
}

func (e *TimesheetStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TimesheetStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TimesheetStatus", str)
	}
	return nil
}

func (e TimesheetStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TimesheetStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TimesheetStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type UserStatus string

const (
	UserStatusActive   UserStatus = "active"
	UserStatusInactive UserStatus = "inactive"
	UserStatusOnLeave  UserStatus = "on_leave"
)

var AllUserStatus = []UserStatus{
	UserStatusActive,
	UserStatusInactive,
	UserStatusOnLeave,
}

func (e UserStatus) IsValid() bool {
	switch e {
	case UserStatusActive, UserStatusInactive, UserStatusOnLeave:
		return true
	}
	return false
}

func (e UserStatus) String() string {
	return string(e)
}

func (e *UserStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserStatus", str)
	}
	return nil
}

func (e UserStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *UserStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e UserStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
