// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/sai18022001/workforce-hub/backend/ent/project"
	"github.com/sai18022001/workforce-hub/backend/ent/projectassignment"
	"github.com/sai18022001/workforce-hub/backend/ent/user"
)

// ProjectAssignment is the model entity for the ProjectAssignment schema.
type ProjectAssignment struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// ProjectRole holds the value of the "project_role" field.
	ProjectRole projectassignment.ProjectRole `json:"project_role,omitempty"`
	// AllocatedHours holds the value of the "allocated_hours" field.
	AllocatedHours float64 `json:"allocated_hours,omitempty"`
	// AssignedAt holds the value of the "assigned_at" field.
	AssignedAt time.Time `json:"assigned_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProjectAssignmentQuery when eager-loading is set.
	Edges               ProjectAssignmentEdges `json:"edges"`
	project_assignments *int
	user_assignments    *int
	selectValues        sql.SelectValues
}

// ProjectAssignmentEdges holds the relations/edges for other nodes in the graph.
type ProjectAssignmentEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Project holds the value of the project edge.
	Project *Project `json:"project,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProjectAssignmentEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// ProjectOrErr returns the Project value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProjectAssignmentEdges) ProjectOrErr() (*Project, error) {
	if e.Project != nil {
		return e.Project, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: project.Label}
	}
	return nil, &NotLoadedError{edge: "project"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProjectAssignment) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case projectassignment.FieldAllocatedHours:
			values[i] = new(sql.NullFloat64)
		case projectassignment.FieldID:
			values[i] = new(sql.NullInt64)
		case projectassignment.FieldProjectRole:
			values[i] = new(sql.NullString)
		case projectassignment.FieldAssignedAt:
			values[i] = new(sql.NullTime)
		case projectassignment.ForeignKeys[0]: // project_assignments
			values[i] = new(sql.NullInt64)
		case projectassignment.ForeignKeys[1]: // user_assignments
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProjectAssignment fields.
func (_m *ProjectAssignment) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case projectassignment.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case projectassignment.FieldProjectRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field project_role", values[i])
			} else if value.Valid {
				_m.ProjectRole = projectassignment.ProjectRole(value.String)
			}
		case projectassignment.FieldAllocatedHours:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field allocated_hours", values[i])
			} else if value.Valid {
				_m.AllocatedHours = value.Float64
			}
		case projectassignment.FieldAssignedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field assigned_at", values[i])
			} else if value.Valid {
				_m.AssignedAt = value.Time
			}
		case projectassignment.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field project_assignments", value)
			} else if value.Valid {
				_m.project_assignments = new(int)
				*_m.project_assignments = int(value.Int64)
			}
		case projectassignment.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_assignments", value)
			} else if value.Valid {
				_m.user_assignments = new(int)
				*_m.user_assignments = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProjectAssignment.
// This includes values selected through modifiers, order, etc.
func (_m *ProjectAssignment) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the ProjectAssignment entity.
func (_m *ProjectAssignment) QueryUser() *UserQuery {
	return NewProjectAssignmentClient(_m.config).QueryUser(_m)
}

// QueryProject queries the "project" edge of the ProjectAssignment entity.
func (_m *ProjectAssignment) QueryProject() *ProjectQuery {
	return NewProjectAssignmentClient(_m.config).QueryProject(_m)
}

// Update returns a builder for updating this ProjectAssignment.
// Note that you need to call ProjectAssignment.Unwrap() before calling this method if this ProjectAssignment
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ProjectAssignment) Update() *ProjectAssignmentUpdateOne {
	return NewProjectAssignmentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ProjectAssignment entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ProjectAssignment) Unwrap() *ProjectAssignment {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProjectAssignment is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ProjectAssignment) String() string {
	var builder strings.Builder
	builder.WriteString("ProjectAssignment(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("project_role=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProjectRole))
	builder.WriteString(", ")
	builder.WriteString("allocated_hours=")
	builder.WriteString(fmt.Sprintf("%v", _m.AllocatedHours))
	builder.WriteString(", ")
	builder.WriteString("assigned_at=")
	builder.WriteString(_m.AssignedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ProjectAssignments is a parsable slice of ProjectAssignment.
type ProjectAssignments []*ProjectAssignment
