// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sai18022001/workforce-hub/backend/ent/project"
	"github.com/sai18022001/workforce-hub/backend/ent/projectassignment"
	"github.com/sai18022001/workforce-hub/backend/ent/user"
)

// ProjectAssignmentCreate is the builder for creating a ProjectAssignment entity.
type ProjectAssignmentCreate struct {
	config
	mutation *ProjectAssignmentMutation
	hooks    []Hook
}

// SetProjectRole sets the "project_role" field.
func (_c *ProjectAssignmentCreate) SetProjectRole(v projectassignment.ProjectRole) *ProjectAssignmentCreate {
	_c.mutation.SetProjectRole(v)
	return _c
}

// SetNillableProjectRole sets the "project_role" field if the given value is not nil.
func (_c *ProjectAssignmentCreate) SetNillableProjectRole(v *projectassignment.ProjectRole) *ProjectAssignmentCreate {
	if v != nil {
		_c.SetProjectRole(*v)
	}
	return _c
}

// SetAllocatedHours sets the "allocated_hours" field.
func (_c *ProjectAssignmentCreate) SetAllocatedHours(v float64) *ProjectAssignmentCreate {
	_c.mutation.SetAllocatedHours(v)
	return _c
}

// SetNillableAllocatedHours sets the "allocated_hours" field if the given value is not nil.
func (_c *ProjectAssignmentCreate) SetNillableAllocatedHours(v *float64) *ProjectAssignmentCreate {
	if v != nil {
		_c.SetAllocatedHours(*v)
	}
	return _c
}

// SetAssignedAt sets the "assigned_at" field.
func (_c *ProjectAssignmentCreate) SetAssignedAt(v time.Time) *ProjectAssignmentCreate {
	_c.mutation.SetAssignedAt(v)
	return _c
}

// SetNillableAssignedAt sets the "assigned_at" field if the given value is not nil.
func (_c *ProjectAssignmentCreate) SetNillableAssignedAt(v *time.Time) *ProjectAssignmentCreate {
	if v != nil {
		_c.SetAssignedAt(*v)
	}
	return _c
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *ProjectAssignmentCreate) SetUserID(id int) *ProjectAssignmentCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *ProjectAssignmentCreate) SetUser(v *User) *ProjectAssignmentCreate {
	return _c.SetUserID(v.ID)
}

// SetProjectID sets the "project" edge to the Project entity by ID.
func (_c *ProjectAssignmentCreate) SetProjectID(id int) *ProjectAssignmentCreate {
	_c.mutation.SetProjectID(id)
	return _c
}

// SetProject sets the "project" edge to the Project entity.
func (_c *ProjectAssignmentCreate) SetProject(v *Project) *ProjectAssignmentCreate {
	return _c.SetProjectID(v.ID)
}

// Mutation returns the ProjectAssignmentMutation object of the builder.
func (_c *ProjectAssignmentCreate) Mutation() *ProjectAssignmentMutation {
	return _c.mutation
}

// Save creates the ProjectAssignment in the database.
func (_c *ProjectAssignmentCreate) Save(ctx context.Context) (*ProjectAssignment, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProjectAssignmentCreate) SaveX(ctx context.Context) *ProjectAssignment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProjectAssignmentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProjectAssignmentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProjectAssignmentCreate) defaults() {
	if _, ok := _c.mutation.ProjectRole(); !ok {
		v := projectassignment.DefaultProjectRole
		_c.mutation.SetProjectRole(v)
	}
	if _, ok := _c.mutation.AllocatedHours(); !ok {
		v := projectassignment.DefaultAllocatedHours
		_c.mutation.SetAllocatedHours(v)
	}
	if _, ok := _c.mutation.AssignedAt(); !ok {
		v := projectassignment.DefaultAssignedAt()
		_c.mutation.SetAssignedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProjectAssignmentCreate) check() error {
	if _, ok := _c.mutation.ProjectRole(); !ok {
		return &ValidationError{Name: "project_role", err: errors.New(`ent: missing required field "ProjectAssignment.project_role"`)}
	}
	if v, ok := _c.mutation.ProjectRole(); ok {
		if err := projectassignment.ProjectRoleValidator(v); err != nil {
			return &ValidationError{Name: "project_role", err: fmt.Errorf(`ent: validator failed for field "ProjectAssignment.project_role": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AllocatedHours(); !ok {
		return &ValidationError{Name: "allocated_hours", err: errors.New(`ent: missing required field "ProjectAssignment.allocated_hours"`)}
	}
	if _, ok := _c.mutation.AssignedAt(); !ok {
		return &ValidationError{Name: "assigned_at", err: errors.New(`ent: missing required field "ProjectAssignment.assigned_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "ProjectAssignment.user"`)}
	}
	if len(_c.mutation.ProjectIDs()) == 0 {
		return &ValidationError{Name: "project", err: errors.New(`ent: missing required edge "ProjectAssignment.project"`)}
	}
	return nil
}

func (_c *ProjectAssignmentCreate) sqlSave(ctx context.Context) (*ProjectAssignment, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProjectAssignmentCreate) createSpec() (*ProjectAssignment, *sqlgraph.CreateSpec) {
	var (
		_node = &ProjectAssignment{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(projectassignment.Table, sqlgraph.NewFieldSpec(projectassignment.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.ProjectRole(); ok {
		_spec.SetField(projectassignment.FieldProjectRole, field.TypeEnum, value)
		_node.ProjectRole = value
	}
	if value, ok := _c.mutation.AllocatedHours(); ok {
		_spec.SetField(projectassignment.FieldAllocatedHours, field.TypeFloat64, value)
		_node.AllocatedHours = value
	}
	if value, ok := _c.mutation.AssignedAt(); ok {
		_spec.SetField(projectassignment.FieldAssignedAt, field.TypeTime, value)
		_node.AssignedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projectassignment.UserTable,
			Columns: []string{projectassignment.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_assignments = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projectassignment.ProjectTable,
			Columns: []string{projectassignment.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.project_assignments = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ProjectAssignmentCreateBulk is the builder for creating many ProjectAssignment entities in bulk.
type ProjectAssignmentCreateBulk struct {
	config
	err      error
	builders []*ProjectAssignmentCreate
}

// Save creates the ProjectAssignment entities in the database.
func (_c *ProjectAssignmentCreateBulk) Save(ctx context.Context) ([]*ProjectAssignment, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ProjectAssignment, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProjectAssignmentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProjectAssignmentCreateBulk) SaveX(ctx context.Context) []*ProjectAssignment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProjectAssignmentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProjectAssignmentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
