// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sai18022001/workforce-hub/backend/ent/predicate"
	"github.com/sai18022001/workforce-hub/backend/ent/project"
	"github.com/sai18022001/workforce-hub/backend/ent/projectassignment"
	"github.com/sai18022001/workforce-hub/backend/ent/user"
)

// ProjectAssignmentUpdate is the builder for updating ProjectAssignment entities.
type ProjectAssignmentUpdate struct {
	config
	hooks    []Hook
	mutation *ProjectAssignmentMutation
}

// Where appends a list predicates to the ProjectAssignmentUpdate builder.
func (_u *ProjectAssignmentUpdate) Where(ps ...predicate.ProjectAssignment) *ProjectAssignmentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProjectRole sets the "project_role" field.
func (_u *ProjectAssignmentUpdate) SetProjectRole(v projectassignment.ProjectRole) *ProjectAssignmentUpdate {
	_u.mutation.SetProjectRole(v)
	return _u
}

// SetNillableProjectRole sets the "project_role" field if the given value is not nil.
func (_u *ProjectAssignmentUpdate) SetNillableProjectRole(v *projectassignment.ProjectRole) *ProjectAssignmentUpdate {
	if v != nil {
		_u.SetProjectRole(*v)
	}
	return _u
}

// SetAllocatedHours sets the "allocated_hours" field.
func (_u *ProjectAssignmentUpdate) SetAllocatedHours(v float64) *ProjectAssignmentUpdate {
	_u.mutation.ResetAllocatedHours()
	_u.mutation.SetAllocatedHours(v)
	return _u
}

// SetNillableAllocatedHours sets the "allocated_hours" field if the given value is not nil.
func (_u *ProjectAssignmentUpdate) SetNillableAllocatedHours(v *float64) *ProjectAssignmentUpdate {
	if v != nil {
		_u.SetAllocatedHours(*v)
	}
	return _u
}

// AddAllocatedHours adds value to the "allocated_hours" field.
func (_u *ProjectAssignmentUpdate) AddAllocatedHours(v float64) *ProjectAssignmentUpdate {
	_u.mutation.AddAllocatedHours(v)
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *ProjectAssignmentUpdate) SetUserID(id int) *ProjectAssignmentUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *ProjectAssignmentUpdate) SetUser(v *User) *ProjectAssignmentUpdate {
	return _u.SetUserID(v.ID)
}

// SetProjectID sets the "project" edge to the Project entity by ID.
func (_u *ProjectAssignmentUpdate) SetProjectID(id int) *ProjectAssignmentUpdate {
	_u.mutation.SetProjectID(id)
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *ProjectAssignmentUpdate) SetProject(v *Project) *ProjectAssignmentUpdate {
	return _u.SetProjectID(v.ID)
}

// Mutation returns the ProjectAssignmentMutation object of the builder.
func (_u *ProjectAssignmentUpdate) Mutation() *ProjectAssignmentMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ProjectAssignmentUpdate) ClearUser() *ProjectAssignmentUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *ProjectAssignmentUpdate) ClearProject() *ProjectAssignmentUpdate {
	_u.mutation.ClearProject()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProjectAssignmentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProjectAssignmentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProjectAssignmentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProjectAssignmentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProjectAssignmentUpdate) check() error {
	if v, ok := _u.mutation.ProjectRole(); ok {
		if err := projectassignment.ProjectRoleValidator(v); err != nil {
			return &ValidationError{Name: "project_role", err: fmt.Errorf(`ent: validator failed for field "ProjectAssignment.project_role": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProjectAssignment.user"`)
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProjectAssignment.project"`)
	}
	return nil
}

func (_u *ProjectAssignmentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(projectassignment.Table, projectassignment.Columns, sqlgraph.NewFieldSpec(projectassignment.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ProjectRole(); ok {
		_spec.SetField(projectassignment.FieldProjectRole, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.AllocatedHours(); ok {
		_spec.SetField(projectassignment.FieldAllocatedHours, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAllocatedHours(); ok {
		_spec.AddField(projectassignment.FieldAllocatedHours, field.TypeFloat64, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projectassignment.UserTable,
			Columns: []string{projectassignment.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projectassignment.UserTable,
			Columns: []string{projectassignment.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projectassignment.ProjectTable,
			Columns: []string{projectassignment.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projectassignment.ProjectTable,
			Columns: []string{projectassignment.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{projectassignment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProjectAssignmentUpdateOne is the builder for updating a single ProjectAssignment entity.
type ProjectAssignmentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProjectAssignmentMutation
}

// SetProjectRole sets the "project_role" field.
func (_u *ProjectAssignmentUpdateOne) SetProjectRole(v projectassignment.ProjectRole) *ProjectAssignmentUpdateOne {
	_u.mutation.SetProjectRole(v)
	return _u
}

// SetNillableProjectRole sets the "project_role" field if the given value is not nil.
func (_u *ProjectAssignmentUpdateOne) SetNillableProjectRole(v *projectassignment.ProjectRole) *ProjectAssignmentUpdateOne {
	if v != nil {
		_u.SetProjectRole(*v)
	}
	return _u
}

// SetAllocatedHours sets the "allocated_hours" field.
func (_u *ProjectAssignmentUpdateOne) SetAllocatedHours(v float64) *ProjectAssignmentUpdateOne {
	_u.mutation.ResetAllocatedHours()
	_u.mutation.SetAllocatedHours(v)
	return _u
}

// SetNillableAllocatedHours sets the "allocated_hours" field if the given value is not nil.
func (_u *ProjectAssignmentUpdateOne) SetNillableAllocatedHours(v *float64) *ProjectAssignmentUpdateOne {
	if v != nil {
		_u.SetAllocatedHours(*v)
	}
	return _u
}

// AddAllocatedHours adds value to the "allocated_hours" field.
func (_u *ProjectAssignmentUpdateOne) AddAllocatedHours(v float64) *ProjectAssignmentUpdateOne {
	_u.mutation.AddAllocatedHours(v)
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *ProjectAssignmentUpdateOne) SetUserID(id int) *ProjectAssignmentUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *ProjectAssignmentUpdateOne) SetUser(v *User) *ProjectAssignmentUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetProjectID sets the "project" edge to the Project entity by ID.
func (_u *ProjectAssignmentUpdateOne) SetProjectID(id int) *ProjectAssignmentUpdateOne {
	_u.mutation.SetProjectID(id)
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *ProjectAssignmentUpdateOne) SetProject(v *Project) *ProjectAssignmentUpdateOne {
	return _u.SetProjectID(v.ID)
}

// Mutation returns the ProjectAssignmentMutation object of the builder.
func (_u *ProjectAssignmentUpdateOne) Mutation() *ProjectAssignmentMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ProjectAssignmentUpdateOne) ClearUser() *ProjectAssignmentUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *ProjectAssignmentUpdateOne) ClearProject() *ProjectAssignmentUpdateOne {
	_u.mutation.ClearProject()
	return _u
}

// Where appends a list predicates to the ProjectAssignmentUpdate builder.
func (_u *ProjectAssignmentUpdateOne) Where(ps ...predicate.ProjectAssignment) *ProjectAssignmentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProjectAssignmentUpdateOne) Select(field string, fields ...string) *ProjectAssignmentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProjectAssignment entity.
func (_u *ProjectAssignmentUpdateOne) Save(ctx context.Context) (*ProjectAssignment, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProjectAssignmentUpdateOne) SaveX(ctx context.Context) *ProjectAssignment {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProjectAssignmentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProjectAssignmentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProjectAssignmentUpdateOne) check() error {
	if v, ok := _u.mutation.ProjectRole(); ok {
		if err := projectassignment.ProjectRoleValidator(v); err != nil {
			return &ValidationError{Name: "project_role", err: fmt.Errorf(`ent: validator failed for field "ProjectAssignment.project_role": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProjectAssignment.user"`)
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProjectAssignment.project"`)
	}
	return nil
}

func (_u *ProjectAssignmentUpdateOne) sqlSave(ctx context.Context) (_node *ProjectAssignment, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(projectassignment.Table, projectassignment.Columns, sqlgraph.NewFieldSpec(projectassignment.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProjectAssignment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, projectassignment.FieldID)
		for _, f := range fields {
			if !projectassignment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != projectassignment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ProjectRole(); ok {
		_spec.SetField(projectassignment.FieldProjectRole, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.AllocatedHours(); ok {
		_spec.SetField(projectassignment.FieldAllocatedHours, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAllocatedHours(); ok {
		_spec.AddField(projectassignment.FieldAllocatedHours, field.TypeFloat64, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projectassignment.UserTable,
			Columns: []string{projectassignment.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projectassignment.UserTable,
			Columns: []string{projectassignment.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projectassignment.ProjectTable,
			Columns: []string{projectassignment.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projectassignment.ProjectTable,
			Columns: []string{projectassignment.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ProjectAssignment{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{projectassignment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
