// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/sai18022001/workforce-hub/backend/ent/department"
	"github.com/sai18022001/workforce-hub/backend/ent/project"
	"github.com/sai18022001/workforce-hub/backend/ent/projectassignment"
	"github.com/sai18022001/workforce-hub/backend/ent/role"
	"github.com/sai18022001/workforce-hub/backend/ent/schema"
	"github.com/sai18022001/workforce-hub/backend/ent/timesheet"
	"github.com/sai18022001/workforce-hub/backend/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	departmentFields := schema.Department{}.Fields()
	_ = departmentFields
	// departmentDescName is the schema descriptor for name field.
	departmentDescName := departmentFields[0].Descriptor()
	// department.NameValidator is a validator for the "name" field. It is called by the builders before save.
	department.NameValidator = departmentDescName.Validators[0].(func(string) error)
	// departmentDescCreatedAt is the schema descriptor for created_at field.
	departmentDescCreatedAt := departmentFields[2].Descriptor()
	// department.DefaultCreatedAt holds the default value on creation for the created_at field.
	department.DefaultCreatedAt = departmentDescCreatedAt.Default.(func() time.Time)
	projectFields := schema.Project{}.Fields()
	_ = projectFields
	// projectDescName is the schema descriptor for name field.
	projectDescName := projectFields[0].Descriptor()
	// project.NameValidator is a validator for the "name" field. It is called by the builders before save.
	project.NameValidator = projectDescName.Validators[0].(func(string) error)
	// projectDescCreatedAt is the schema descriptor for created_at field.
	projectDescCreatedAt := projectFields[5].Descriptor()
	// project.DefaultCreatedAt holds the default value on creation for the created_at field.
	project.DefaultCreatedAt = projectDescCreatedAt.Default.(func() time.Time)
	// projectDescUpdatedAt is the schema descriptor for updated_at field.
	projectDescUpdatedAt := projectFields[6].Descriptor()
	// project.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	project.DefaultUpdatedAt = projectDescUpdatedAt.Default.(func() time.Time)
	// project.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	project.UpdateDefaultUpdatedAt = projectDescUpdatedAt.UpdateDefault.(func() time.Time)
	projectassignmentFields := schema.ProjectAssignment{}.Fields()
	_ = projectassignmentFields
	// projectassignmentDescAllocatedHours is the schema descriptor for allocated_hours field.
	projectassignmentDescAllocatedHours := projectassignmentFields[1].Descriptor()
	// projectassignment.DefaultAllocatedHours holds the default value on creation for the allocated_hours field.
	projectassignment.DefaultAllocatedHours = projectassignmentDescAllocatedHours.Default.(float64)
	// projectassignmentDescAssignedAt is the schema descriptor for assigned_at field.
	projectassignmentDescAssignedAt := projectassignmentFields[2].Descriptor()
	// projectassignment.DefaultAssignedAt holds the default value on creation for the assigned_at field.
	projectassignment.DefaultAssignedAt = projectassignmentDescAssignedAt.Default.(func() time.Time)
	roleFields := schema.Role{}.Fields()
	_ = roleFields
	// roleDescName is the schema descriptor for name field.
	roleDescName := roleFields[0].Descriptor()
	// role.NameValidator is a validator for the "name" field. It is called by the builders before save.
	role.NameValidator = roleDescName.Validators[0].(func(string) error)
	// roleDescCreatedAt is the schema descriptor for created_at field.
	roleDescCreatedAt := roleFields[2].Descriptor()
	// role.DefaultCreatedAt holds the default value on creation for the created_at field.
	role.DefaultCreatedAt = roleDescCreatedAt.Default.(func() time.Time)
	timesheetFields := schema.Timesheet{}.Fields()
	_ = timesheetFields
	// timesheetDescHoursWorked is the schema descriptor for hours_worked field.
	timesheetDescHoursWorked := timesheetFields[1].Descriptor()
	// timesheet.HoursWorkedValidator is a validator for the "hours_worked" field. It is called by the builders before save.
	timesheet.HoursWorkedValidator = timesheetDescHoursWorked.Validators[0].(func(float64) error)
	// timesheetDescCreatedAt is the schema descriptor for created_at field.
	timesheetDescCreatedAt := timesheetFields[4].Descriptor()
	// timesheet.DefaultCreatedAt holds the default value on creation for the created_at field.
	timesheet.DefaultCreatedAt = timesheetDescCreatedAt.Default.(func() time.Time)
	// timesheetDescUpdatedAt is the schema descriptor for updated_at field.
	timesheetDescUpdatedAt := timesheetFields[5].Descriptor()
	// timesheet.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	timesheet.DefaultUpdatedAt = timesheetDescUpdatedAt.Default.(func() time.Time)
	// timesheet.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	timesheet.UpdateDefaultUpdatedAt = timesheetDescUpdatedAt.UpdateDefault.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescFirstName is the schema descriptor for first_name field.
	userDescFirstName := userFields[0].Descriptor()
	// user.FirstNameValidator is a validator for the "first_name" field. It is called by the builders before save.
	user.FirstNameValidator = userDescFirstName.Validators[0].(func(string) error)
	// userDescLastName is the schema descriptor for last_name field.
	userDescLastName := userFields[1].Descriptor()
	// user.LastNameValidator is a validator for the "last_name" field. It is called by the builders before save.
	user.LastNameValidator = userDescLastName.Validators[0].(func(string) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[2].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[3].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = userDescPasswordHash.Validators[0].(func(string) error)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[5].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[6].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
}
