// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sai18022001/workforce-hub/backend/ent/project"
	"github.com/sai18022001/workforce-hub/backend/ent/timesheet"
	"github.com/sai18022001/workforce-hub/backend/ent/user"
)

// TimesheetCreate is the builder for creating a Timesheet entity.
type TimesheetCreate struct {
	config
	mutation *TimesheetMutation
	hooks    []Hook
}

// SetDate sets the "date" field.
func (_c *TimesheetCreate) SetDate(v time.Time) *TimesheetCreate {
	_c.mutation.SetDate(v)
	return _c
}

// SetHoursWorked sets the "hours_worked" field.
func (_c *TimesheetCreate) SetHoursWorked(v float64) *TimesheetCreate {
	_c.mutation.SetHoursWorked(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *TimesheetCreate) SetDescription(v string) *TimesheetCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *TimesheetCreate) SetNillableDescription(v *string) *TimesheetCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *TimesheetCreate) SetStatus(v timesheet.Status) *TimesheetCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *TimesheetCreate) SetNillableStatus(v *timesheet.Status) *TimesheetCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TimesheetCreate) SetCreatedAt(v time.Time) *TimesheetCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TimesheetCreate) SetNillableCreatedAt(v *time.Time) *TimesheetCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TimesheetCreate) SetUpdatedAt(v time.Time) *TimesheetCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TimesheetCreate) SetNillableUpdatedAt(v *time.Time) *TimesheetCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *TimesheetCreate) SetUserID(id int) *TimesheetCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *TimesheetCreate) SetUser(v *User) *TimesheetCreate {
	return _c.SetUserID(v.ID)
}

// SetProjectID sets the "project" edge to the Project entity by ID.
func (_c *TimesheetCreate) SetProjectID(id int) *TimesheetCreate {
	_c.mutation.SetProjectID(id)
	return _c
}

// SetProject sets the "project" edge to the Project entity.
func (_c *TimesheetCreate) SetProject(v *Project) *TimesheetCreate {
	return _c.SetProjectID(v.ID)
}

// Mutation returns the TimesheetMutation object of the builder.
func (_c *TimesheetCreate) Mutation() *TimesheetMutation {
	return _c.mutation
}

// Save creates the Timesheet in the database.
func (_c *TimesheetCreate) Save(ctx context.Context) (*Timesheet, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TimesheetCreate) SaveX(ctx context.Context) *Timesheet {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TimesheetCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TimesheetCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TimesheetCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := timesheet.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := timesheet.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := timesheet.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TimesheetCreate) check() error {
	if _, ok := _c.mutation.Date(); !ok {
		return &ValidationError{Name: "date", err: errors.New(`ent: missing required field "Timesheet.date"`)}
	}
	if _, ok := _c.mutation.HoursWorked(); !ok {
		return &ValidationError{Name: "hours_worked", err: errors.New(`ent: missing required field "Timesheet.hours_worked"`)}
	}
	if v, ok := _c.mutation.HoursWorked(); ok {
		if err := timesheet.HoursWorkedValidator(v); err != nil {
			return &ValidationError{Name: "hours_worked", err: fmt.Errorf(`ent: validator failed for field "Timesheet.hours_worked": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Timesheet.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := timesheet.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Timesheet.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Timesheet.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Timesheet.updated_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Timesheet.user"`)}
	}
	if len(_c.mutation.ProjectIDs()) == 0 {
		return &ValidationError{Name: "project", err: errors.New(`ent: missing required edge "Timesheet.project"`)}
	}
	return nil
}

func (_c *TimesheetCreate) sqlSave(ctx context.Context) (*Timesheet, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TimesheetCreate) createSpec() (*Timesheet, *sqlgraph.CreateSpec) {
	var (
		_node = &Timesheet{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(timesheet.Table, sqlgraph.NewFieldSpec(timesheet.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Date(); ok {
		_spec.SetField(timesheet.FieldDate, field.TypeTime, value)
		_node.Date = value
	}
	if value, ok := _c.mutation.HoursWorked(); ok {
		_spec.SetField(timesheet.FieldHoursWorked, field.TypeFloat64, value)
		_node.HoursWorked = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(timesheet.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(timesheet.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(timesheet.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(timesheet.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   timesheet.UserTable,
			Columns: []string{timesheet.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_timesheets = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   timesheet.ProjectTable,
			Columns: []string{timesheet.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.project_timesheets = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TimesheetCreateBulk is the builder for creating many Timesheet entities in bulk.
type TimesheetCreateBulk struct {
	config
	err      error
	builders []*TimesheetCreate
}

// Save creates the Timesheet entities in the database.
func (_c *TimesheetCreateBulk) Save(ctx context.Context) ([]*Timesheet, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Timesheet, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TimesheetMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TimesheetCreateBulk) SaveX(ctx context.Context) []*Timesheet {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TimesheetCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TimesheetCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
