// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sai18022001/workforce-hub/backend/ent/predicate"
	"github.com/sai18022001/workforce-hub/backend/ent/project"
	"github.com/sai18022001/workforce-hub/backend/ent/timesheet"
	"github.com/sai18022001/workforce-hub/backend/ent/user"
)

// TimesheetUpdate is the builder for updating Timesheet entities.
type TimesheetUpdate struct {
	config
	hooks    []Hook
	mutation *TimesheetMutation
}

// Where appends a list predicates to the TimesheetUpdate builder.
func (_u *TimesheetUpdate) Where(ps ...predicate.Timesheet) *TimesheetUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDate sets the "date" field.
func (_u *TimesheetUpdate) SetDate(v time.Time) *TimesheetUpdate {
	_u.mutation.SetDate(v)
	return _u
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (_u *TimesheetUpdate) SetNillableDate(v *time.Time) *TimesheetUpdate {
	if v != nil {
		_u.SetDate(*v)
	}
	return _u
}

// SetHoursWorked sets the "hours_worked" field.
func (_u *TimesheetUpdate) SetHoursWorked(v float64) *TimesheetUpdate {
	_u.mutation.ResetHoursWorked()
	_u.mutation.SetHoursWorked(v)
	return _u
}

// SetNillableHoursWorked sets the "hours_worked" field if the given value is not nil.
func (_u *TimesheetUpdate) SetNillableHoursWorked(v *float64) *TimesheetUpdate {
	if v != nil {
		_u.SetHoursWorked(*v)
	}
	return _u
}

// AddHoursWorked adds value to the "hours_worked" field.
func (_u *TimesheetUpdate) AddHoursWorked(v float64) *TimesheetUpdate {
	_u.mutation.AddHoursWorked(v)
	return _u
}

// SetDescription sets the "description" field.
func (_u *TimesheetUpdate) SetDescription(v string) *TimesheetUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TimesheetUpdate) SetNillableDescription(v *string) *TimesheetUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *TimesheetUpdate) ClearDescription() *TimesheetUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetStatus sets the "status" field.
func (_u *TimesheetUpdate) SetStatus(v timesheet.Status) *TimesheetUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TimesheetUpdate) SetNillableStatus(v *timesheet.Status) *TimesheetUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TimesheetUpdate) SetUpdatedAt(v time.Time) *TimesheetUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *TimesheetUpdate) SetUserID(id int) *TimesheetUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *TimesheetUpdate) SetUser(v *User) *TimesheetUpdate {
	return _u.SetUserID(v.ID)
}

// SetProjectID sets the "project" edge to the Project entity by ID.
func (_u *TimesheetUpdate) SetProjectID(id int) *TimesheetUpdate {
	_u.mutation.SetProjectID(id)
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *TimesheetUpdate) SetProject(v *Project) *TimesheetUpdate {
	return _u.SetProjectID(v.ID)
}

// Mutation returns the TimesheetMutation object of the builder.
func (_u *TimesheetUpdate) Mutation() *TimesheetMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *TimesheetUpdate) ClearUser() *TimesheetUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *TimesheetUpdate) ClearProject() *TimesheetUpdate {
	_u.mutation.ClearProject()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TimesheetUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TimesheetUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TimesheetUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TimesheetUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TimesheetUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := timesheet.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TimesheetUpdate) check() error {
	if v, ok := _u.mutation.HoursWorked(); ok {
		if err := timesheet.HoursWorkedValidator(v); err != nil {
			return &ValidationError{Name: "hours_worked", err: fmt.Errorf(`ent: validator failed for field "Timesheet.hours_worked": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := timesheet.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Timesheet.status": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Timesheet.user"`)
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Timesheet.project"`)
	}
	return nil
}

func (_u *TimesheetUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(timesheet.Table, timesheet.Columns, sqlgraph.NewFieldSpec(timesheet.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Date(); ok {
		_spec.SetField(timesheet.FieldDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.HoursWorked(); ok {
		_spec.SetField(timesheet.FieldHoursWorked, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedHoursWorked(); ok {
		_spec.AddField(timesheet.FieldHoursWorked, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(timesheet.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(timesheet.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(timesheet.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(timesheet.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   timesheet.UserTable,
			Columns: []string{timesheet.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   timesheet.UserTable,
			Columns: []string{timesheet.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   timesheet.ProjectTable,
			Columns: []string{timesheet.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   timesheet.ProjectTable,
			Columns: []string{timesheet.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{timesheet.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TimesheetUpdateOne is the builder for updating a single Timesheet entity.
type TimesheetUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TimesheetMutation
}

// SetDate sets the "date" field.
func (_u *TimesheetUpdateOne) SetDate(v time.Time) *TimesheetUpdateOne {
	_u.mutation.SetDate(v)
	return _u
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (_u *TimesheetUpdateOne) SetNillableDate(v *time.Time) *TimesheetUpdateOne {
	if v != nil {
		_u.SetDate(*v)
	}
	return _u
}

// SetHoursWorked sets the "hours_worked" field.
func (_u *TimesheetUpdateOne) SetHoursWorked(v float64) *TimesheetUpdateOne {
	_u.mutation.ResetHoursWorked()
	_u.mutation.SetHoursWorked(v)
	return _u
}

// SetNillableHoursWorked sets the "hours_worked" field if the given value is not nil.
func (_u *TimesheetUpdateOne) SetNillableHoursWorked(v *float64) *TimesheetUpdateOne {
	if v != nil {
		_u.SetHoursWorked(*v)
	}
	return _u
}

// AddHoursWorked adds value to the "hours_worked" field.
func (_u *TimesheetUpdateOne) AddHoursWorked(v float64) *TimesheetUpdateOne {
	_u.mutation.AddHoursWorked(v)
	return _u
}

// SetDescription sets the "description" field.
func (_u *TimesheetUpdateOne) SetDescription(v string) *TimesheetUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TimesheetUpdateOne) SetNillableDescription(v *string) *TimesheetUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *TimesheetUpdateOne) ClearDescription() *TimesheetUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetStatus sets the "status" field.
func (_u *TimesheetUpdateOne) SetStatus(v timesheet.Status) *TimesheetUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TimesheetUpdateOne) SetNillableStatus(v *timesheet.Status) *TimesheetUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TimesheetUpdateOne) SetUpdatedAt(v time.Time) *TimesheetUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *TimesheetUpdateOne) SetUserID(id int) *TimesheetUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *TimesheetUpdateOne) SetUser(v *User) *TimesheetUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetProjectID sets the "project" edge to the Project entity by ID.
func (_u *TimesheetUpdateOne) SetProjectID(id int) *TimesheetUpdateOne {
	_u.mutation.SetProjectID(id)
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *TimesheetUpdateOne) SetProject(v *Project) *TimesheetUpdateOne {
	return _u.SetProjectID(v.ID)
}

// Mutation returns the TimesheetMutation object of the builder.
func (_u *TimesheetUpdateOne) Mutation() *TimesheetMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *TimesheetUpdateOne) ClearUser() *TimesheetUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *TimesheetUpdateOne) ClearProject() *TimesheetUpdateOne {
	_u.mutation.ClearProject()
	return _u
}

// Where appends a list predicates to the TimesheetUpdate builder.
func (_u *TimesheetUpdateOne) Where(ps ...predicate.Timesheet) *TimesheetUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TimesheetUpdateOne) Select(field string, fields ...string) *TimesheetUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Timesheet entity.
func (_u *TimesheetUpdateOne) Save(ctx context.Context) (*Timesheet, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TimesheetUpdateOne) SaveX(ctx context.Context) *Timesheet {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TimesheetUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TimesheetUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TimesheetUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := timesheet.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TimesheetUpdateOne) check() error {
	if v, ok := _u.mutation.HoursWorked(); ok {
		if err := timesheet.HoursWorkedValidator(v); err != nil {
			return &ValidationError{Name: "hours_worked", err: fmt.Errorf(`ent: validator failed for field "Timesheet.hours_worked": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := timesheet.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Timesheet.status": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Timesheet.user"`)
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Timesheet.project"`)
	}
	return nil
}

func (_u *TimesheetUpdateOne) sqlSave(ctx context.Context) (_node *Timesheet, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(timesheet.Table, timesheet.Columns, sqlgraph.NewFieldSpec(timesheet.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Timesheet.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, timesheet.FieldID)
		for _, f := range fields {
			if !timesheet.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != timesheet.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Date(); ok {
		_spec.SetField(timesheet.FieldDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.HoursWorked(); ok {
		_spec.SetField(timesheet.FieldHoursWorked, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedHoursWorked(); ok {
		_spec.AddField(timesheet.FieldHoursWorked, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(timesheet.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(timesheet.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(timesheet.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(timesheet.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   timesheet.UserTable,
			Columns: []string{timesheet.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   timesheet.UserTable,
			Columns: []string{timesheet.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   timesheet.ProjectTable,
			Columns: []string{timesheet.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   timesheet.ProjectTable,
			Columns: []string{timesheet.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Timesheet{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{timesheet.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
