// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sai18022001/workforce-hub/backend/ent/predicate"
	"github.com/sai18022001/workforce-hub/backend/ent/timesheet"
)

// TimesheetDelete is the builder for deleting a Timesheet entity.
type TimesheetDelete struct {
	config
	hooks    []Hook
	mutation *TimesheetMutation
}

// Where appends a list predicates to the TimesheetDelete builder.
func (_d *TimesheetDelete) Where(ps ...predicate.Timesheet) *TimesheetDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *TimesheetDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TimesheetDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *TimesheetDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(timesheet.Table, sqlgraph.NewFieldSpec(timesheet.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// TimesheetDeleteOne is the builder for deleting a single Timesheet entity.
type TimesheetDeleteOne struct {
	_d *TimesheetDelete
}

// Where appends a list predicates to the TimesheetDelete builder.
func (_d *TimesheetDeleteOne) Where(ps ...predicate.Timesheet) *TimesheetDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *TimesheetDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{timesheet.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TimesheetDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
