// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/sai18022001/workforce-hub/backend/ent/project"
	"github.com/sai18022001/workforce-hub/backend/ent/timesheet"
	"github.com/sai18022001/workforce-hub/backend/ent/user"
)

// Timesheet is the model entity for the Timesheet schema.
type Timesheet struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Date holds the value of the "date" field.
	Date time.Time `json:"date,omitempty"`
	// HoursWorked holds the value of the "hours_worked" field.
	HoursWorked float64 `json:"hours_worked,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Status holds the value of the "status" field.
	Status timesheet.Status `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TimesheetQuery when eager-loading is set.
	Edges              TimesheetEdges `json:"edges"`
	project_timesheets *int
	user_timesheets    *int
	selectValues       sql.SelectValues
}

// TimesheetEdges holds the relations/edges for other nodes in the graph.
type TimesheetEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Project holds the value of the project edge.
	Project *Project `json:"project,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TimesheetEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// ProjectOrErr returns the Project value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TimesheetEdges) ProjectOrErr() (*Project, error) {
	if e.Project != nil {
		return e.Project, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: project.Label}
	}
	return nil, &NotLoadedError{edge: "project"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Timesheet) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case timesheet.FieldHoursWorked:
			values[i] = new(sql.NullFloat64)
		case timesheet.FieldID:
			values[i] = new(sql.NullInt64)
		case timesheet.FieldDescription, timesheet.FieldStatus:
			values[i] = new(sql.NullString)
		case timesheet.FieldDate, timesheet.FieldCreatedAt, timesheet.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case timesheet.ForeignKeys[0]: // project_timesheets
			values[i] = new(sql.NullInt64)
		case timesheet.ForeignKeys[1]: // user_timesheets
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Timesheet fields.
func (_m *Timesheet) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case timesheet.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case timesheet.FieldDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date", values[i])
			} else if value.Valid {
				_m.Date = value.Time
			}
		case timesheet.FieldHoursWorked:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field hours_worked", values[i])
			} else if value.Valid {
				_m.HoursWorked = value.Float64
			}
		case timesheet.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case timesheet.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = timesheet.Status(value.String)
			}
		case timesheet.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case timesheet.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case timesheet.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field project_timesheets", value)
			} else if value.Valid {
				_m.project_timesheets = new(int)
				*_m.project_timesheets = int(value.Int64)
			}
		case timesheet.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_timesheets", value)
			} else if value.Valid {
				_m.user_timesheets = new(int)
				*_m.user_timesheets = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Timesheet.
// This includes values selected through modifiers, order, etc.
func (_m *Timesheet) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the Timesheet entity.
func (_m *Timesheet) QueryUser() *UserQuery {
	return NewTimesheetClient(_m.config).QueryUser(_m)
}

// QueryProject queries the "project" edge of the Timesheet entity.
func (_m *Timesheet) QueryProject() *ProjectQuery {
	return NewTimesheetClient(_m.config).QueryProject(_m)
}

// Update returns a builder for updating this Timesheet.
// Note that you need to call Timesheet.Unwrap() before calling this method if this Timesheet
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Timesheet) Update() *TimesheetUpdateOne {
	return NewTimesheetClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Timesheet entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Timesheet) Unwrap() *Timesheet {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Timesheet is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Timesheet) String() string {
	var builder strings.Builder
	builder.WriteString("Timesheet(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("date=")
	builder.WriteString(_m.Date.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("hours_worked=")
	builder.WriteString(fmt.Sprintf("%v", _m.HoursWorked))
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Timesheets is a parsable slice of Timesheet.
type Timesheets []*Timesheet
