// Code generated by ent, DO NOT EDIT.

package timesheet

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/sai18022001/workforce-hub/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Timesheet {
	return predicate.Timesheet(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Timesheet {
	return predicate.Timesheet(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Timesheet {
	return predicate.Timesheet(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Timesheet {
	return predicate.Timesheet(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Timesheet {
	return predicate.Timesheet(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Timesheet {
	return predicate.Timesheet(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Timesheet {
	return predicate.Timesheet(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Timesheet {
	return predicate.Timesheet(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Timesheet {
	return predicate.Timesheet(sql.FieldLTE(FieldID, id))
}

// Date applies equality check predicate on the "date" field. It's identical to DateEQ.
func Date(v time.Time) predicate.Timesheet {
	return predicate.Timesheet(sql.FieldEQ(FieldDate, v))
}

// HoursWorked applies equality check predicate on the "hours_worked" field. It's identical to HoursWorkedEQ.
func HoursWorked(v float64) predicate.Timesheet {
	return predicate.Timesheet(sql.FieldEQ(FieldHoursWorked, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Timesheet {
	return predicate.Timesheet(sql.FieldEQ(FieldDescription, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Timesheet {
	return predicate.Timesheet(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Timesheet {
	return predicate.Timesheet(sql.FieldEQ(FieldUpdatedAt, v))
}

// DateEQ applies the EQ predicate on the "date" field.
func DateEQ(v time.Time) predicate.Timesheet {
	return predicate.Timesheet(sql.FieldEQ(FieldDate, v))
}

// DateNEQ applies the NEQ predicate on the "date" field.
func DateNEQ(v time.Time) predicate.Timesheet {
	return predicate.Timesheet(sql.FieldNEQ(FieldDate, v))
}

// DateIn applies the In predicate on the "date" field.
func DateIn(vs ...time.Time) predicate.Timesheet {
	return predicate.Timesheet(sql.FieldIn(FieldDate, vs...))
}

// DateNotIn applies the NotIn predicate on the "date" field.
func DateNotIn(vs ...time.Time) predicate.Timesheet {
	return predicate.Timesheet(sql.FieldNotIn(FieldDate, vs...))
}

// DateGT applies the GT predicate on the "date" field.
func DateGT(v time.Time) predicate.Timesheet {
	return predicate.Timesheet(sql.FieldGT(FieldDate, v))
}

// DateGTE applies the GTE predicate on the "date" field.
func DateGTE(v time.Time) predicate.Timesheet {
	return predicate.Timesheet(sql.FieldGTE(FieldDate, v))
}

// DateLT applies the LT predicate on the "date" field.
func DateLT(v time.Time) predicate.Timesheet {
	return predicate.Timesheet(sql.FieldLT(FieldDate, v))
}

// DateLTE applies the LTE predicate on the "date" field.
func DateLTE(v time.Time) predicate.Timesheet {
	return predicate.Timesheet(sql.FieldLTE(FieldDate, v))
}

// HoursWorkedEQ applies the EQ predicate on the "hours_worked" field.
func HoursWorkedEQ(v float64) predicate.Timesheet {
	return predicate.Timesheet(sql.FieldEQ(FieldHoursWorked, v))
}

// HoursWorkedNEQ applies the NEQ predicate on the "hours_worked" field.
func HoursWorkedNEQ(v float64) predicate.Timesheet {
	return predicate.Timesheet(sql.FieldNEQ(FieldHoursWorked, v))
}

// HoursWorkedIn applies the In predicate on the "hours_worked" field.
func HoursWorkedIn(vs ...float64) predicate.Timesheet {
	return predicate.Timesheet(sql.FieldIn(FieldHoursWorked, vs...))
}

// HoursWorkedNotIn applies the NotIn predicate on the "hours_worked" field.
func HoursWorkedNotIn(vs ...float64) predicate.Timesheet {
	return predicate.Timesheet(sql.FieldNotIn(FieldHoursWorked, vs...))
}

// HoursWorkedGT applies the GT predicate on the "hours_worked" field.
func HoursWorkedGT(v float64) predicate.Timesheet {
	return predicate.Timesheet(sql.FieldGT(FieldHoursWorked, v))
}

// HoursWorkedGTE applies the GTE predicate on the "hours_worked" field.
func HoursWorkedGTE(v float64) predicate.Timesheet {
	return predicate.Timesheet(sql.FieldGTE(FieldHoursWorked, v))
}

// HoursWorkedLT applies the LT predicate on the "hours_worked" field.
func HoursWorkedLT(v float64) predicate.Timesheet {
	return predicate.Timesheet(sql.FieldLT(FieldHoursWorked, v))
}

// HoursWorkedLTE applies the LTE predicate on the "hours_worked" field.
func HoursWorkedLTE(v float64) predicate.Timesheet {
	return predicate.Timesheet(sql.FieldLTE(FieldHoursWorked, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Timesheet {
	return predicate.Timesheet(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Timesheet {
	return predicate.Timesheet(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Timesheet {
	return predicate.Timesheet(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Timesheet {
	return predicate.Timesheet(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Timesheet {
	return predicate.Timesheet(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Timesheet {
	return predicate.Timesheet(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Timesheet {
	return predicate.Timesheet(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Timesheet {
	return predicate.Timesheet(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Timesheet {
	return predicate.Timesheet(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Timesheet {
	return predicate.Timesheet(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Timesheet {
	return predicate.Timesheet(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Timesheet {
	return predicate.Timesheet(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Timesheet {
	return predicate.Timesheet(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Timesheet {
	return predicate.Timesheet(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Timesheet {
	return predicate.Timesheet(sql.FieldContainsFold(FieldDescription, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Timesheet {
	return predicate.Timesheet(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Timesheet {
	return predicate.Timesheet(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Timesheet {
	return predicate.Timesheet(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Timesheet {
	return predicate.Timesheet(sql.FieldNotIn(FieldStatus, vs...))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Timesheet {
	return predicate.Timesheet(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Timesheet {
	return predicate.Timesheet(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Timesheet {
	return predicate.Timesheet(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Timesheet {
	return predicate.Timesheet(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Timesheet {
	return predicate.Timesheet(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Timesheet {
	return predicate.Timesheet(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Timesheet {
	return predicate.Timesheet(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Timesheet {
	return predicate.Timesheet(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Timesheet {
	return predicate.Timesheet(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Timesheet {
	return predicate.Timesheet(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Timesheet {
	return predicate.Timesheet(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Timesheet {
	return predicate.Timesheet(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Timesheet {
	return predicate.Timesheet(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Timesheet {
	return predicate.Timesheet(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Timesheet {
	return predicate.Timesheet(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Timesheet {
	return predicate.Timesheet(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Timesheet {
	return predicate.Timesheet(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Timesheet {
	return predicate.Timesheet(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasProject applies the HasEdge predicate on the "project" edge.
func HasProject() predicate.Timesheet {
	return predicate.Timesheet(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProjectTable, ProjectColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProjectWith applies the HasEdge predicate on the "project" edge with a given conditions (other predicates).
func HasProjectWith(preds ...predicate.Project) predicate.Timesheet {
	return predicate.Timesheet(func(s *sql.Selector) {
		step := newProjectStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Timesheet) predicate.Timesheet {
	return predicate.Timesheet(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Timesheet) predicate.Timesheet {
	return predicate.Timesheet(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Timesheet) predicate.Timesheet {
	return predicate.Timesheet(sql.NotPredicates(p))
}
