package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"
	"strconv"

	"github.com/sai18022001/workforce-hub/backend/ent/department"
	"github.com/sai18022001/workforce-hub/backend/ent/project"
	"github.com/sai18022001/workforce-hub/backend/ent/projectassignment"
	"github.com/sai18022001/workforce-hub/backend/ent/timesheet"
	"github.com/sai18022001/workforce-hub/backend/ent/user"
	"github.com/sai18022001/workforce-hub/backend/graph/generated"
	"github.com/sai18022001/workforce-hub/backend/graph/model"
	"golang.org/x/crypto/bcrypt"
)

// ── AUTH ──────────────────────────────────────────────────────────────────────

func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.AuthPayload, error) {
	hash, err := bcrypt.GenerateFromPassword([]byte(input.Password), 12)
	if err != nil {
		return nil, fmt.Errorf("failed to hash password: %w", err)
	}
	roleID, err := strconv.Atoi(input.RoleID)
	if err != nil {
		return nil, fmt.Errorf("invalid role ID")
	}
	deptID, err := strconv.Atoi(input.DepartmentID)
	if err != nil {
		return nil, fmt.Errorf("invalid department ID")
	}
	u, err := r.DB.User.Create().
		SetFirstName(input.FirstName).
		SetLastName(input.LastName).
		SetEmail(input.Email).
		SetPasswordHash(string(hash)).
		SetRoleID(roleID).
		SetDepartmentID(deptID).
		Save(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to create user: %w", err)
	}
	token, err := generateJWT(u.ID)
	if err != nil {
		return nil, err
	}
	return &model.AuthPayload{Token: token, User: entUserToModel(u)}, nil
}

func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthPayload, error) {
	u, err := r.DB.User.Query().
		Where(user.EmailEQ(input.Email)).
		Only(ctx)
	if err != nil {
		return nil, fmt.Errorf("invalid email or password")
	}
	if err := bcrypt.CompareHashAndPassword([]byte(u.PasswordHash), []byte(input.Password)); err != nil {
		return nil, fmt.Errorf("invalid email or password")
	}
	token, err := generateJWT(u.ID)
	if err != nil {
		return nil, err
	}
	return &model.AuthPayload{Token: token, User: entUserToModel(u)}, nil
}

// ── DEPARTMENT ────────────────────────────────────────────────────────────────

func (r *mutationResolver) CreateDepartment(ctx context.Context, input model.CreateDepartmentInput) (*model.Department, error) {
	q := r.DB.Department.Create().SetName(input.Name)
	if input.Description != nil {
		q = q.SetDescription(*input.Description)
	}
	d, err := q.Save(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to create department: %w", err)
	}
	return entDepartmentToModel(d), nil
}

// ── PROJECT ───────────────────────────────────────────────────────────────────

func (r *mutationResolver) CreateProject(ctx context.Context, input model.CreateProjectInput) (*model.Project, error) {
	deptID, err := strconv.Atoi(input.DepartmentID)
	if err != nil {
		return nil, fmt.Errorf("invalid department ID")
	}
	q := r.DB.Project.Create().
		SetName(input.Name).
		SetDepartmentID(deptID)
	if input.Description != nil {
		q = q.SetDescription(*input.Description)
	}
	if input.StartDate != nil {
		q = q.SetStartDate(*input.StartDate)
	}
	if input.EndDate != nil {
		q = q.SetEndDate(*input.EndDate)
	}
	p, err := q.Save(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to create project: %w", err)
	}
	return entProjectToModel(p), nil
}

func (r *mutationResolver) UpdateProject(ctx context.Context, id string, input model.UpdateProjectInput) (*model.Project, error) {
	pid, err := strconv.Atoi(id)
	if err != nil {
		return nil, fmt.Errorf("invalid project ID")
	}
	q := r.DB.Project.UpdateOneID(pid)
	if input.Name != nil {
		q = q.SetName(*input.Name)
	}
	if input.Description != nil {
		q = q.SetDescription(*input.Description)
	}
	if input.Status != nil {
		q = q.SetStatus(project.Status(string(*input.Status)))
	}
	if input.StartDate != nil {
		q = q.SetStartDate(*input.StartDate)
	}
	if input.EndDate != nil {
		q = q.SetEndDate(*input.EndDate)
	}
	p, err := q.Save(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to update project: %w", err)
	}
	return entProjectToModel(p), nil
}

func (r *mutationResolver) DeleteProject(ctx context.Context, id string) (bool, error) {
	pid, err := strconv.Atoi(id)
	if err != nil {
		return false, fmt.Errorf("invalid project ID")
	}
	if err := r.DB.Project.DeleteOneID(pid).Exec(ctx); err != nil {
		return false, fmt.Errorf("failed to delete project: %w", err)
	}
	return true, nil
}

// ── ASSIGNMENTS ───────────────────────────────────────────────────────────────

func (r *mutationResolver) AssignUserToProject(ctx context.Context, input model.AssignUserInput) (*model.ProjectAssignment, error) {
	uid, err := strconv.Atoi(input.UserID)
	if err != nil {
		return nil, fmt.Errorf("invalid user ID")
	}
	pid, err := strconv.Atoi(input.ProjectID)
	if err != nil {
		return nil, fmt.Errorf("invalid project ID")
	}
	a, err := r.DB.ProjectAssignment.Create().
		SetUserID(uid).
		SetProjectID(pid).
		SetProjectRole(projectassignment.ProjectRole(string(input.ProjectRole))).
		SetAllocatedHours(input.AllocatedHours).
		Save(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to assign user: %w", err)
	}
	return entAssignmentToModel(a), nil
}

func (r *mutationResolver) RemoveUserFromProject(ctx context.Context, assignmentID string) (bool, error) {
	aid, err := strconv.Atoi(assignmentID)
	if err != nil {
		return false, fmt.Errorf("invalid assignment ID")
	}
	if err := r.DB.ProjectAssignment.DeleteOneID(aid).Exec(ctx); err != nil {
		return false, fmt.Errorf("failed to remove assignment: %w", err)
	}
	return true, nil
}

// ── TIMESHEETS ────────────────────────────────────────────────────────────────

func (r *mutationResolver) LogTimesheet(ctx context.Context, input model.LogTimesheetInput) (*model.Timesheet, error) {
	uid, err := strconv.Atoi(input.UserID)
	if err != nil {
		return nil, fmt.Errorf("invalid user ID")
	}
	pid, err := strconv.Atoi(input.ProjectID)
	if err != nil {
		return nil, fmt.Errorf("invalid project ID")
	}
	q := r.DB.Timesheet.Create().
		SetUserID(uid).
		SetProjectID(pid).
		SetDate(input.Date).
		SetHoursWorked(input.HoursWorked)
	if input.Description != nil {
		q = q.SetDescription(*input.Description)
	}
	t, err := q.Save(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to log timesheet: %w", err)
	}
	return entTimesheetToModel(t), nil
}

func (r *mutationResolver) UpdateTimesheetStatus(ctx context.Context, input model.UpdateTimesheetStatusInput) (*model.Timesheet, error) {
	tid, err := strconv.Atoi(input.TimesheetID)
	if err != nil {
		return nil, fmt.Errorf("invalid timesheet ID")
	}
	t, err := r.DB.Timesheet.UpdateOneID(tid).
		SetStatus(timesheet.Status(string(input.Status))).
		Save(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to update timesheet status: %w", err)
	}
	return entTimesheetToModel(t), nil
}

// ── QUERIES ───────────────────────────────────────────────────────────────────

func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	// Will be implemented in Phase 5 with JWT middleware
	return nil, fmt.Errorf("auth middleware not yet implemented")
}

func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	users, err := r.DB.User.Query().All(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]*model.User, len(users))
	for i, u := range users {
		result[i] = entUserToModel(u)
	}
	return result, nil
}

func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	uid, err := strconv.Atoi(id)
	if err != nil {
		return nil, fmt.Errorf("invalid user ID")
	}
	u, err := r.DB.User.Get(ctx, uid)
	if err != nil {
		return nil, err
	}
	return entUserToModel(u), nil
}

func (r *queryResolver) Departments(ctx context.Context) ([]*model.Department, error) {
	depts, err := r.DB.Department.Query().All(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]*model.Department, len(depts))
	for i, d := range depts {
		result[i] = entDepartmentToModel(d)
	}
	return result, nil
}

func (r *queryResolver) Department(ctx context.Context, id string) (*model.Department, error) {
	did, err := strconv.Atoi(id)
	if err != nil {
		return nil, fmt.Errorf("invalid department ID")
	}
	d, err := r.DB.Department.Get(ctx, did)
	if err != nil {
		return nil, err
	}
	return entDepartmentToModel(d), nil
}

func (r *queryResolver) Roles(ctx context.Context) ([]*model.Role, error) {
	roles, err := r.DB.Role.Query().All(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]*model.Role, len(roles))
	for i, role := range roles {
		result[i] = entRoleToModel(role)
	}
	return result, nil
}

func (r *queryResolver) Projects(ctx context.Context) ([]*model.Project, error) {
	projects, err := r.DB.Project.Query().All(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]*model.Project, len(projects))
	for i, p := range projects {
		result[i] = entProjectToModel(p)
	}
	return result, nil
}

func (r *queryResolver) Project(ctx context.Context, id string) (*model.Project, error) {
	pid, err := strconv.Atoi(id)
	if err != nil {
		return nil, fmt.Errorf("invalid project ID")
	}
	p, err := r.DB.Project.Get(ctx, pid)
	if err != nil {
		return nil, err
	}
	return entProjectToModel(p), nil
}

func (r *queryResolver) ProjectsByDepartment(ctx context.Context, departmentID string) ([]*model.Project, error) {
	did, err := strconv.Atoi(departmentID)
	if err != nil {
		return nil, fmt.Errorf("invalid department ID")
	}
	projects, err := r.DB.Project.Query().
		Where(project.HasDepartmentWith(department.IDEQ(did))).
		All(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]*model.Project, len(projects))
	for i, p := range projects {
		result[i] = entProjectToModel(p)
	}
	return result, nil
}

func (r *queryResolver) Timesheets(ctx context.Context, userID string) ([]*model.Timesheet, error) {
	uid, err := strconv.Atoi(userID)
	if err != nil {
		return nil, fmt.Errorf("invalid user ID")
	}
	sheets, err := r.DB.Timesheet.Query().
		Where(timesheet.HasUserWith(user.IDEQ(uid))).
		All(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]*model.Timesheet, len(sheets))
	for i, t := range sheets {
		result[i] = entTimesheetToModel(t)
	}
	return result, nil
}

func (r *queryResolver) PendingTimesheets(ctx context.Context) ([]*model.Timesheet, error) {
	sheets, err := r.DB.Timesheet.Query().
		Where(timesheet.StatusEQ(timesheet.StatusSubmitted)).
		All(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]*model.Timesheet, len(sheets))
	for i, t := range sheets {
		result[i] = entTimesheetToModel(t)
	}
	return result, nil
}

func (r *queryResolver) DashboardStats(ctx context.Context) (*model.DashboardStats, error) {
	totalUsers, _ := r.DB.User.Query().Count(ctx)
	totalProjects, _ := r.DB.Project.Query().Count(ctx)
	activeProjects, _ := r.DB.Project.Query().
		Where(project.StatusEQ(project.StatusActive)).
		Count(ctx)
	sheets, _ := r.DB.Timesheet.Query().
		Where(timesheet.StatusEQ(timesheet.StatusApproved)).
		All(ctx)
	var totalHours float64
	for _, s := range sheets {
		totalHours += s.HoursWorked
	}
	return &model.DashboardStats{
		TotalUsers:       totalUsers,
		TotalProjects:    totalProjects,
		ActiveProjects:   activeProjects,
		TotalHoursLogged: totalHours,
	}, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }