// Code generated by ent, DO NOT EDIT.

package projectassignment

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the projectassignment type in the database.
	Label = "project_assignment"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldProjectRole holds the string denoting the project_role field in the database.
	FieldProjectRole = "project_role"
	// FieldAllocatedHours holds the string denoting the allocated_hours field in the database.
	FieldAllocatedHours = "allocated_hours"
	// FieldAssignedAt holds the string denoting the assigned_at field in the database.
	FieldAssignedAt = "assigned_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeProject holds the string denoting the project edge name in mutations.
	EdgeProject = "project"
	// Table holds the table name of the projectassignment in the database.
	Table = "project_assignments"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "project_assignments"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_assignments"
	// ProjectTable is the table that holds the project relation/edge.
	ProjectTable = "project_assignments"
	// ProjectInverseTable is the table name for the Project entity.
	// It exists in this package in order to avoid circular dependency with the "project" package.
	ProjectInverseTable = "projects"
	// ProjectColumn is the table column denoting the project relation/edge.
	ProjectColumn = "project_assignments"
)

// Columns holds all SQL columns for projectassignment fields.
var Columns = []string{
	FieldID,
	FieldProjectRole,
	FieldAllocatedHours,
	FieldAssignedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "project_assignments"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"project_assignments",
	"user_assignments",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultAllocatedHours holds the default value on creation for the "allocated_hours" field.
	DefaultAllocatedHours float64
	// DefaultAssignedAt holds the default value on creation for the "assigned_at" field.
	DefaultAssignedAt func() time.Time
)

// ProjectRole defines the type for the "project_role" enum field.
type ProjectRole string

// ProjectRoleDeveloper is the default value of the ProjectRole enum.
const DefaultProjectRole = ProjectRoleDeveloper

// ProjectRole values.
const (
	ProjectRoleLead      ProjectRole = "lead"
	ProjectRoleDeveloper ProjectRole = "developer"
	ProjectRoleDesigner  ProjectRole = "designer"
	ProjectRoleTester    ProjectRole = "tester"
	ProjectRoleAnalyst   ProjectRole = "analyst"
)

func (pr ProjectRole) String() string {
	return string(pr)
}

// ProjectRoleValidator is a validator for the "project_role" field enum values. It is called by the builders before save.
func ProjectRoleValidator(pr ProjectRole) error {
	switch pr {
	case ProjectRoleLead, ProjectRoleDeveloper, ProjectRoleDesigner, ProjectRoleTester, ProjectRoleAnalyst:
		return nil
	default:
		return fmt.Errorf("projectassignment: invalid enum value for project_role field: %q", pr)
	}
}

// OrderOption defines the ordering options for the ProjectAssignment queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByProjectRole orders the results by the project_role field.
func ByProjectRole(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProjectRole, opts...).ToFunc()
}

// ByAllocatedHours orders the results by the allocated_hours field.
func ByAllocatedHours(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAllocatedHours, opts...).ToFunc()
}

// ByAssignedAt orders the results by the assigned_at field.
func ByAssignedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAssignedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByProjectField orders the results by project field.
func ByProjectField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProjectStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newProjectStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProjectInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ProjectTable, ProjectColumn),
	)
}
