// Code generated by ent, DO NOT EDIT.

package projectassignment

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/sai18022001/workforce-hub/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ProjectAssignment {
	return predicate.ProjectAssignment(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ProjectAssignment {
	return predicate.ProjectAssignment(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ProjectAssignment {
	return predicate.ProjectAssignment(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ProjectAssignment {
	return predicate.ProjectAssignment(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ProjectAssignment {
	return predicate.ProjectAssignment(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ProjectAssignment {
	return predicate.ProjectAssignment(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ProjectAssignment {
	return predicate.ProjectAssignment(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ProjectAssignment {
	return predicate.ProjectAssignment(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ProjectAssignment {
	return predicate.ProjectAssignment(sql.FieldLTE(FieldID, id))
}

// AllocatedHours applies equality check predicate on the "allocated_hours" field. It's identical to AllocatedHoursEQ.
func AllocatedHours(v float64) predicate.ProjectAssignment {
	return predicate.ProjectAssignment(sql.FieldEQ(FieldAllocatedHours, v))
}

// AssignedAt applies equality check predicate on the "assigned_at" field. It's identical to AssignedAtEQ.
func AssignedAt(v time.Time) predicate.ProjectAssignment {
	return predicate.ProjectAssignment(sql.FieldEQ(FieldAssignedAt, v))
}

// ProjectRoleEQ applies the EQ predicate on the "project_role" field.
func ProjectRoleEQ(v ProjectRole) predicate.ProjectAssignment {
	return predicate.ProjectAssignment(sql.FieldEQ(FieldProjectRole, v))
}

// ProjectRoleNEQ applies the NEQ predicate on the "project_role" field.
func ProjectRoleNEQ(v ProjectRole) predicate.ProjectAssignment {
	return predicate.ProjectAssignment(sql.FieldNEQ(FieldProjectRole, v))
}

// ProjectRoleIn applies the In predicate on the "project_role" field.
func ProjectRoleIn(vs ...ProjectRole) predicate.ProjectAssignment {
	return predicate.ProjectAssignment(sql.FieldIn(FieldProjectRole, vs...))
}

// ProjectRoleNotIn applies the NotIn predicate on the "project_role" field.
func ProjectRoleNotIn(vs ...ProjectRole) predicate.ProjectAssignment {
	return predicate.ProjectAssignment(sql.FieldNotIn(FieldProjectRole, vs...))
}

// AllocatedHoursEQ applies the EQ predicate on the "allocated_hours" field.
func AllocatedHoursEQ(v float64) predicate.ProjectAssignment {
	return predicate.ProjectAssignment(sql.FieldEQ(FieldAllocatedHours, v))
}

// AllocatedHoursNEQ applies the NEQ predicate on the "allocated_hours" field.
func AllocatedHoursNEQ(v float64) predicate.ProjectAssignment {
	return predicate.ProjectAssignment(sql.FieldNEQ(FieldAllocatedHours, v))
}

// AllocatedHoursIn applies the In predicate on the "allocated_hours" field.
func AllocatedHoursIn(vs ...float64) predicate.ProjectAssignment {
	return predicate.ProjectAssignment(sql.FieldIn(FieldAllocatedHours, vs...))
}

// AllocatedHoursNotIn applies the NotIn predicate on the "allocated_hours" field.
func AllocatedHoursNotIn(vs ...float64) predicate.ProjectAssignment {
	return predicate.ProjectAssignment(sql.FieldNotIn(FieldAllocatedHours, vs...))
}

// AllocatedHoursGT applies the GT predicate on the "allocated_hours" field.
func AllocatedHoursGT(v float64) predicate.ProjectAssignment {
	return predicate.ProjectAssignment(sql.FieldGT(FieldAllocatedHours, v))
}

// AllocatedHoursGTE applies the GTE predicate on the "allocated_hours" field.
func AllocatedHoursGTE(v float64) predicate.ProjectAssignment {
	return predicate.ProjectAssignment(sql.FieldGTE(FieldAllocatedHours, v))
}

// AllocatedHoursLT applies the LT predicate on the "allocated_hours" field.
func AllocatedHoursLT(v float64) predicate.ProjectAssignment {
	return predicate.ProjectAssignment(sql.FieldLT(FieldAllocatedHours, v))
}

// AllocatedHoursLTE applies the LTE predicate on the "allocated_hours" field.
func AllocatedHoursLTE(v float64) predicate.ProjectAssignment {
	return predicate.ProjectAssignment(sql.FieldLTE(FieldAllocatedHours, v))
}

// AssignedAtEQ applies the EQ predicate on the "assigned_at" field.
func AssignedAtEQ(v time.Time) predicate.ProjectAssignment {
	return predicate.ProjectAssignment(sql.FieldEQ(FieldAssignedAt, v))
}

// AssignedAtNEQ applies the NEQ predicate on the "assigned_at" field.
func AssignedAtNEQ(v time.Time) predicate.ProjectAssignment {
	return predicate.ProjectAssignment(sql.FieldNEQ(FieldAssignedAt, v))
}

// AssignedAtIn applies the In predicate on the "assigned_at" field.
func AssignedAtIn(vs ...time.Time) predicate.ProjectAssignment {
	return predicate.ProjectAssignment(sql.FieldIn(FieldAssignedAt, vs...))
}

// AssignedAtNotIn applies the NotIn predicate on the "assigned_at" field.
func AssignedAtNotIn(vs ...time.Time) predicate.ProjectAssignment {
	return predicate.ProjectAssignment(sql.FieldNotIn(FieldAssignedAt, vs...))
}

// AssignedAtGT applies the GT predicate on the "assigned_at" field.
func AssignedAtGT(v time.Time) predicate.ProjectAssignment {
	return predicate.ProjectAssignment(sql.FieldGT(FieldAssignedAt, v))
}

// AssignedAtGTE applies the GTE predicate on the "assigned_at" field.
func AssignedAtGTE(v time.Time) predicate.ProjectAssignment {
	return predicate.ProjectAssignment(sql.FieldGTE(FieldAssignedAt, v))
}

// AssignedAtLT applies the LT predicate on the "assigned_at" field.
func AssignedAtLT(v time.Time) predicate.ProjectAssignment {
	return predicate.ProjectAssignment(sql.FieldLT(FieldAssignedAt, v))
}

// AssignedAtLTE applies the LTE predicate on the "assigned_at" field.
func AssignedAtLTE(v time.Time) predicate.ProjectAssignment {
	return predicate.ProjectAssignment(sql.FieldLTE(FieldAssignedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.ProjectAssignment {
	return predicate.ProjectAssignment(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.ProjectAssignment {
	return predicate.ProjectAssignment(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasProject applies the HasEdge predicate on the "project" edge.
func HasProject() predicate.ProjectAssignment {
	return predicate.ProjectAssignment(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProjectTable, ProjectColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProjectWith applies the HasEdge predicate on the "project" edge with a given conditions (other predicates).
func HasProjectWith(preds ...predicate.Project) predicate.ProjectAssignment {
	return predicate.ProjectAssignment(func(s *sql.Selector) {
		step := newProjectStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ProjectAssignment) predicate.ProjectAssignment {
	return predicate.ProjectAssignment(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ProjectAssignment) predicate.ProjectAssignment {
	return predicate.ProjectAssignment(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ProjectAssignment) predicate.ProjectAssignment {
	return predicate.ProjectAssignment(sql.NotPredicates(p))
}
